### ISSUE TITLE
request release

### ISSUE THREAD

**Issue by lrlunin** [AvonReppert/udkm#2]
I would like to add this repository to my docker image. Can you please create a release or tag or either tell which commit is stable to use.
Thanks!

**Comment by AvonReppert** [comment]
Thx for the request,
 I made a release at the current state 
[https://github.com/AvonReppert/udkm/releases/tag/v0.0.1]

you are very welcome to include the package in your docker file. 
As described, the package is designed for data analysis for specific setups in the udkm group in Potsdam. The only methods that are somewhat more general can be found in the `tools ` module. 

The repository is currently 0.9 Gb large because it contains a lot of example data that is setup specific. I am not sure if that is an issue for you.
